### ISSUE TITLE
react version 16.0.0  与 ant-design 当前版本兼容性问题记录

### ISSUE THREAD

**Issue by buptsky** [OurBizTask/BizTask#7]
由于使用了react 16.0.0 最新版本，与当前版本的ant-design(2.13.4)存在兼容问题，造成项目目前存在以下问题
1. 使用 Menu组件时报警告
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.null
在antd的相关issue: 
https://github.com/ant-design/ant-design/issues/7754
https://github.com/ant-design/ant-design/issues/5377

2. 下拉组件Select和与下拉框原理类似的AutoComplete组件在首次进行下拉展示时，下拉项与下拉框的宽度不一致，对使用造成一定影响（问题效果见issue）
在antd的相关issue:
https://github.com/ant-design/ant-design/issues/7609

解决方法：回退react版本到15.x.x 或 等待antd进行相关bug修复

**Comment by elevensky** [comment]
貌似tooltip组件也有问题。

**Comment by buptsky** [comment]
@elevensky 可能还有其他的，暂时可以考虑回退react版本吧

**Comment by afc163** [comment]
1 和 2 应该都已经修复了。
